name: Build and Deploy
on:
  pull_request:
    types:
      - closed
    branches:
      - main
jobs:
  build-and-deploy:
    name: Build and Deploy em Produção
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Faz build e deploy do projeto
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: /home/debian/scripts/build-deploy.sh